### ISSUE TITLE
uploadMaxSize sanitizer autoresize not working

### ISSUE THREAD

**Issue by fullflash** [MihailDev/yii2-elfinder#71]
I am uploading image with 6000x3000, 3mb, with none unicode character 
i have this configs but no result no resize no size reducing and sanitizing sluggable not work either.

elfinder version 
**Version: 2.1.14, protocol version: 2.1
jQuery/jQuery UI: 2.2.4/1.11.4**

```
'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\PathController',
            'access' => ['@'],
            'root' => [
                'path' => '/global',
//                'name' => 'Files'
                'baseUrl'=>$params["siteRootUrl"].'upload',
                'basePath'=>'@frontend/web/upload',
                'name'=>['category'=>"app","message"=>"Assets"]
//                'name' => Yii::t("app","Assets")
            ],
            'watermark' => [
                'source'         => __DIR__.'/logo.png', // Path to Water mark image
                'marginRight'    => 5,          // Margin right pixel
                'marginBottom'   => 5,          // Margin bottom pixel
                'quality'        => 95,         // JPEG image save quality
                'transparency'   => 70,         // Water mark image transparency ( other than PNG )
                'targetType'     => IMG_GIF|IMG_JPG|IMG_PNG|IMG_WBMP, // Target image formats ( bit-field )
                'targetMinPixel' => 200         // Target image minimum pixel size
            ],

            'connectOptions' => [
                'bind' => array(
                    'mkdir.pre mkfile.pre rename.pre archive.pre' => array(
                        'Plugin.Sluggable.cmdPreprocess'
                    ),
                    'upload.presave' => array(
                        'Plugin.Sluggable.onUpLoadPreSave',
                        'Plugin.AutoResize.onUpLoadPreSave'
                    )
                ),
                'uploadMaxSize'=>'1M',
                'plugin' => [
                    'Sluggable' => [
                        'enable' => true,
                        'lowercase' => false,
                        'replacement' => '-'

                    ],
                    'AutoResize' => [
                        'enable' => true,
                        'maxWidth'  => 1000,
                        'maxHeight'  => 1000,
                        'quality' => 90
                    ],
                ],
            ],
        ]
    ],
```

**Comment by fullflash** [comment]
```
 exception 'yii\base\ErrorException' with message 'Call to undefined method elFinder::getOptionsPlugin()' in project...\\vendor\studio-42\elfinder\php\plugins\Normalizer\plugin.php:132
Stack trace:
#0 project...\\vendor\studio-42\elfinder\php\elFinder.class.php(702): elFinderPluginNormalizer->cmdPreprocess()
#1 project...\\vendor\studio-42\elfinder\php\elFinder.class.php(702): ::call_user_func_array:{project...\\vendor\studio-42\elfinder\php\elFinder.class.php:702}()
#2 project...\\vendor\studio-42\elfinder\php\elFinderConnector.class.php(125): elFinder->exec()
#3 project...\\vendor\mihaildev\yii2-elfinder\views\connect.php(10): elFinderConnector->run()
#4 project...\\vendor\yiisoft\yii2\base\View.php(325): ::unknown()
#5 project...\\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile()
#6 project...\\vendor\yiisoft\yii2\base\Controller.php(421): yii\base\View->renderFile()
#7 project...\\vendor\mihaildev\yii2-elfinder\BaseController.php(56): yii\base\Controller->renderFile()
#8 project...\\vendor\yiisoft\yii2\base\InlineAction.php(55): mihaildev\elfinder\BaseController->actionConnect()
#9 project...\\vendor\yiisoft\yii2\base\InlineAction.php(55): ::call_user_func_array:{project...\\vendor\yiisoft\yii2\base\InlineAction.php:55}()
#10 project...\\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams()
#11 project...\\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller->runAction()
#12 project...\\vendor\yiisoft\yii2\web\Application.php(87): yii\base\Module->runAction()
#13 project...\\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest()
#14 project...\\backend\web\index.php(18): yii\base\Application->run()
#15 {main}
```

**Comment by fullflash** [comment]
exception 'yii\base\ErrorException' with message 'Call to undefined method elFinder::getOptionsPlugin()' in project...\\vendor\studio-42\elfinder\php\plugins\Normalizer\plugin.php:132
Stack trace:
#0 project...\\vendor\studio-42\elfinder\php\elFinder.class.php(702): elFinderPluginNormalizer->cmdPreprocess()
#1 project...\\vendor\studio-42\elfinder\php\elFinder.class.php(702): ::call_user_func_array:{project...\\vendor\studio-42\elfinder\php\elFinder.class.php:702}()
#2 project...\\vendor\studio-42\elfinder\php\elFinderConnector.class.php(125): elFinder->exec()
#3 project...\\vendor\mihaildev\yii2-elfinder\views\connect.php(10): elFinderConnector->run()
#4 project...\\vendor\yiisoft\yii2\base\View.php(325): ::unknown()
#5 project...\\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile()
#6 project...\\vendor\yiisoft\yii2\base\Controller.php(421): yii\base\View->renderFile()
#7 project...\\vendor\mihaildev\yii2-elfinder\BaseController.php(56): yii\base\Controller->renderFile()
#8 project...\\vendor\yiisoft\yii2\base\InlineAction.php(55): mihaildev\elfinder\BaseController->actionConnect()
#9 project...\\vendor\yiisoft\yii2\base\InlineAction.php(55): ::call_user_func_array:{project...\\vendor\yiisoft\yii2\base\InlineAction.php:55}()
#10 project...\\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams()
#11 project...\\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller->runAction()
#12 project...\\vendor\yiisoft\yii2\web\Application.php(87): yii\base\Module->runAction()
#13 project...\\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest()
#14 project...\\backend\web\index.php(18): yii\base\Application->run()
#15 {main}

**Comment by fullflash** [comment]
```
 exception 'yii\base\ErrorException' with message 'Call to undefined method elFinder::getOptionsPlugin()' in project...\\vendor\studio-42\elfinder\php\plugins\Normalizer\plugin.php:132
Stack trace:
#0 project...\\vendor\studio-42\elfinder\php\elFinder.class.php(702): elFinderPluginNormalizer->cmdPreprocess()
#1 project...\\vendor\studio-42\elfinder\php\elFinder.class.php(702): ::call_user_func_array:{project...\\vendor\studio-42\elfinder\php\elFinder.class.php:702}()
#2 project...\\vendor\studio-42\elfinder\php\elFinderConnector.class.php(125): elFinder->exec()
#3 project...\\vendor\mihaildev\yii2-elfinder\views\connect.php(10): elFinderConnector->run()
#4 project...\\vendor\yiisoft\yii2\base\View.php(325): ::unknown()
#5 project...\\vendor\yiisoft\yii2\base\View.php(247): yii\base\View->renderPhpFile()
#6 project...\\vendor\yiisoft\yii2\base\Controller.php(421): yii\base\View->renderFile()
#7 project...\\vendor\mihaildev\yii2-elfinder\BaseController.php(56): yii\base\Controller->renderFile()
#8 project...\\vendor\yiisoft\yii2\base\InlineAction.php(55): mihaildev\elfinder\BaseController->actionConnect()
#9 project...\\vendor\yiisoft\yii2\base\InlineAction.php(55): ::call_user_func_array:{project...\\vendor\yiisoft\yii2\base\InlineAction.php:55}()
#10 project...\\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams()
#11 project...\\vendor\yiisoft\yii2\base\Module.php(454): yii\base\Controller->runAction()
#12 project...\\vendor\yiisoft\yii2\web\Application.php(87): yii\base\Module->runAction()
#13 project...\\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest()
#14 project...\\backend\web\index.php(18): yii\base\Application->run()
#15 {main}
```
